#!/bin/bash

#SBATCH --ntasks=1            
#SBATCH --mem=6000            
#SBATCH --time=00:30:00       
#SBATCH --partition=standard    
#SBATCH --account=your_allocation
#SBATCH --array=1-10

module purge
module load anaconda
conda create -n nexus_env python=3.9 --yes
conda activate nexus_env
conda install transformers
python --version
python hello.py $SLURM_ARRAY_TASK_ID
ls
